"""worker_passes — the platform's own pulse

Revision ID: 0027_worker_passes
Revises: 0026_deployment_classification

WHY THIS EXISTS: a pass record must outlive everything the worker depends on, so it's a
TABLE, not a Redis key — under any eviction policy a Redis marker is evictable, and absence
is the only signal that can detect a crashlooping worker; a spurious eviction would fire the
staleness alarm just as a real outage would go undetected.

Three things the autogenerated draft got wrong, corrected here rather than in a follow-up
(this revision never left the branch): it proposed dropping `ix_app_registry_project_id`
(pre-existing drift, unrelated — a migration must not quietly drop someone else's index); its
enum literals were the member NAMES (`OK`/`FAILED`) instead of the values every other enum
here stores, invisible from Python since `PassOutcome` is a `StrEnum` but silently returning
nothing from `WHERE outcome = 'failed'`; and `counts` was `sa.JSON`, which Postgres renders
as text — re-parsed per read, un-indexable, no containment operators.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0027_worker_passes"
down_revision: str | Sequence[str] | None = "0026_deployment_classification"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The native worker_pass_outcome enum, spelled in VALUES like every other enum here.
# create_type=False so THIS migration owns the lifecycle: explicit .create() in upgrade, .drop()
# in downgrade.
worker_pass_outcome = postgresql.ENUM(
    "ok",
    "declined",
    "failed",
    name="worker_pass_outcome",
    create_type=False,
)


def upgrade() -> None:
    worker_pass_outcome.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "worker_passes",
        sa.Column("task_name", sa.String(length=128), nullable=False),
        sa.Column("outcome", worker_pass_outcome, nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detail", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_passes_finished_at"), "worker_passes", ["finished_at"], unique=False
    )
    op.create_index(
        op.f("ix_worker_passes_task_name"), "worker_passes", ["task_name"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_worker_passes_task_name"), table_name="worker_passes")
    op.drop_index(op.f("ix_worker_passes_finished_at"), table_name="worker_passes")
    op.drop_table("worker_passes")
    worker_pass_outcome.drop(op.get_bind(), checkfirst=True)
